### ISSUE TITLE
请问可以预览富文本中的图片吗

### ISSUE THREAD

**Issue by lp13762436965** [csonchen/wxParse#1]
请问可以预览富文本中的图片吗

**Comment by csonchen** [comment]
> 请问可以预览富文本中的图片吗

现在还不可以，多谢提醒，我今天加上哈

**Comment by csonchen** [comment]
@lp13762436965 现在还不可以，多谢提醒，我今天加上哈

**Comment by lp13762436965** [comment]
> > 请问可以预览富文本中的图片吗
> 
> 现在还不可以，多谢提醒，我今天加上哈

加好了@一哈,谢谢哈

**Comment by csonchen** [comment]
@lp13762436965 搞定啦，你可以拉下来试试哈

**Comment by lp13762436965** [comment]
行, 我晚上回去试试
