### ISSUE TITLE
富文本内容含多张图片时，只显示出第一张图片

### ISSUE THREAD

**Issue by CFish-AI** [csonchen/wxParse#10]
富文本内容含多张图片时，只显示出第一张图片，其他的都是显示Loading状态！

代码片段：https://developers.weixin.qq.com/s/VWopxGmL73i8

![image](https://user-images.githubusercontent.com/64966179/86870353-d6744800-c10a-11ea-84e5-6f6db91b8aa5.png)

![image](https://user-images.githubusercontent.com/64966179/86871349-b0e83e00-c10c-11ea-886f-1d1d785302f5.png)

**Comment by CFish-AI** [comment]
经测试，如果富文本中连续多张图片，分别在段落p标签中的话，就都可以显示出来。img标签连续的情况，是经常存在的，还是希望作者能够兼容一下。

![image](https://user-images.githubusercontent.com/64966179/86871654-4b488180-c10d-11ea-8647-eac56221c301.png)

![image](https://user-images.githubusercontent.com/64966179/86871685-5a2f3400-c10d-11ea-811f-dc359afa5bc6.png)

**Comment by csonchen** [comment]
@CFish-AI 谢谢反馈，我现在修复一下

**Comment by csonchen** [comment]
@CFish-AI 已经修复完毕了，你可以直接克隆[wxParse项目](https://github.com/csonchen/wxParse)，然后用components目录下的wxParse组件的代码；也可以更新一下package.json的wx-minicomponent版本为1.0.8，就可以用了，谢谢你的反馈哈

**Comment by CFish-AI** [comment]
@csonchen 已下载来使用了，也谢谢你能这么快的处理！
