### ISSUE TITLE
图片优化后不是行内块内容，不能居中展示

### ISSUE THREAD

**Issue by zhongqianguang** [csonchen/wxParse#13]
<p style="text-align: center;">11111111</p>↵<p style="text-align: center;">1111<br /><img src="https://oss.wejuji.cn/uploads/picture/dahoutai/2020-07-29/w0Xk9ugAx-rGA2gsU-1596000114942.png" alt="" width="292" height="292" /></p>↵<p style="text-align: center;">222</p>

贴上解析的字符串

**Comment by csonchen** [comment]
@zhongqianguang 可以贴一下html代码吗
