### ISSUE TITLE
a标签可以渲染出来，但是点击无法跳转

### ISSUE THREAD

**Issue by yucunying** [csonchen/wxParse#14]

**Comment by csonchen** [comment]
@yucunying 已经可以使用了，但是npm包我还发不上去，你可以先用原生的替换一下

**Comment by yucunying** [comment]
您好，大佬，打扰了
有个疑问想请您解答下
web-view跳转第三方链接后 ，左上角是怎么实现显示返回的？
我本地拉了wxParse的代码，没有找到该效果的设置


这是您写的，点击第三方链接后，显示为返回。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "csonchen/wxParse"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月5日(星期三) 下午4:08
收件人:&nbsp;"csonchen/wxParse"<wxParse@noreply.github.com&gt;;
抄送:&nbsp;"余存颖"<694779762@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [csonchen/wxParse] a标签可以渲染出来，但是点击无法跳转 (#14)





 
@yucunying 已经可以使用了，但是npm包我还发不上去，你可以先用原生的替换一下

**Comment by csonchen** [comment]
@yucunying 这是原生的navigate跳转的呀，自定义了页面放置了原生的webview标签，把href设置进去就可以了
