### ISSUE TITLE
表格渲染出多边框和显示不全的问题 附html源码

### ISSUE THREAD

**Issue by greyovo** [csonchen/wxParse#16]
源码放在了[Ubuntu Paste](https://paste.ubuntu.com/p/mGxYTXjQWR/)上（只放了表格片段，其他片段效果很好:D ）：

直接渲染效果如图，太长了无法显示完全
![image](https://user-images.githubusercontent.com/20888390/89429204-def28980-d76f-11ea-924c-98f175c2e945.png)

起初以为是宽度过大导致的，然后修改了总宽度为260之后如图（是不是因为居中的问题？）：
![image](https://user-images.githubusercontent.com/20888390/89429240-eade4b80-d76f-11ea-86f5-7099088ed6a7.png)

上面放的源码是修改了宽度为260之后的。

因为是直接爬取的学校网站的页面，所以样式设置的会比较复杂。
如果是源码的问题的话可以指导一下怎么处理源码比较好吗？谢谢大佬。

祝好。

**Comment by csonchen** [comment]
@greyovo 首先解答一下表格向右偏移的问题：因为table设置了一个margin-left属性，你可以去掉，如下图所示：
![image](https://user-images.githubusercontent.com/5915045/89480099-13ddfb00-d7c7-11ea-8de8-e461b869c116.png)

**Comment by greyovo** [comment]
> @greyovo 首先解答一下表格向右偏移的问题：因为table设置了一个margin-left属性，你可以去掉，如下图所示：
> ![image](https://user-images.githubusercontent.com/5915045/89480099-13ddfb00-d7c7-11ea-8de8-e461b869c116.png)

非常感谢！

**Comment by csonchen** [comment]
@greyovo 因为表格元素我也内嵌了style属性，导致你这个已经有了style的html元素在生成微信标签的时候，会内嵌到微信原生标签上；我优化了一下代码，你重新拉取一下，我把表格相关元素的style样式内嵌去掉了，效果展示如下：
![image](https://user-images.githubusercontent.com/5915045/89481054-7b954580-d7c9-11ea-8cdb-8b062623ece7.png)
