### ISSUE TITLE
不知道能否实现文本长按可选/复制？

### ISSUE THREAD

**Issue by greyovo** [csonchen/wxParse#17]
😃

**Comment by csonchen** [comment]
你是想文本自行选中，然后出现复制功能；还是只是长按复制全部富文本的内容呢？

**Comment by greyovo** [comment]
@csonchen 希望是前者，文本自行选中，然后出现复制功能

**Comment by csonchen** [comment]
@greyovo 原生的已经实现文本节点的选中复制功能，你可以拉下来替换一下；npm的包我整合多一些小优化再发版了

**Comment by greyovo** [comment]
@greyovo 好的 我试一下

**Comment by greyovo** [comment]
@csonchen 十分感谢 可以完美使用！
