### ISSUE TITLE
无法获取到图片标签上的宽高，而使用了图片源的宽高

### ISSUE THREAD

**Issue by wulanx0920** [csonchen/wxParse#19]
例如一张图片解析前是`<img src="xxxxx" alt="" width="200" height="100">`这样，但在实际解析的时候是直接去获取图片源的宽高，然后使用那个宽高，无视了标签上的宽高，导致在富文本编辑器中修改图片大小没反应，这个问题是否能改善

**Comment by csonchen** [comment]
@wulanx0920 可以实现的，但是有可能采用用户自定义的width，height属性，转换成内设小程序的image图片的，有可能会出现失真或者拉伸

**Comment by wulanx0920** [comment]
@csonchen 虽然会出现失真或者拉伸，但需求就是这样，开发也不需要考虑这些情况，反正是产品提的需求，而且之前停止维护的那个解析器好像也是没有读取图片的宽高。目前这个需求被我先顶过去了，不知道甲方会不会再提，太难了

**Comment by csonchen** [comment]
@wulanx0920 满足你了，原生的可以用了，你更新一下代码；npm的包，我晚点发一版，你看一下哈
![image](https://user-images.githubusercontent.com/5915045/90365000-b59efb00-e097-11ea-8422-4c3245783875.png)

**Comment by wulanx0920** [comment]
@csonchen 太强了

**Comment by csonchen** [comment]
谢谢支持哈
