### ISSUE TITLE
为什么传入的 html 没有显示出来？

### ISSUE THREAD

**Issue by SeanChense** [csonchen/wxParse#2]
显示的是硬编码进去的示例内容

https://github.com/csonchen/wxParse/blob/master/pages/index/index.js#L40

按这个写法引用的

`<wxParse nodes="{{ htmlText }}" />`

**Comment by csonchen** [comment]
@SeanChense 你要提供一下代码片段，我才能去帮你看下

**Comment by xiaoyu1035355110** [comment]
使用npm引用  
```
//json
"usingComponents": {
    "wxParse": "/miniprogram_npm/wx-minicomponent/wxParse"
  },
//js

  content  :  <p>sadfdsafsadfsdf</p>

//wxml
<wxParse nodes="{{ content }}" language="html" />
```
无法解析

**Comment by xiaoyu1035355110** [comment]
@csonchen

**Comment by csonchen** [comment]
![image](https://user-images.githubusercontent.com/5915045/83592608-4f710480-a58d-11ea-9617-fff5f2d0fdfc.png)
亲测没问题 @xiaoyu1035355110

**Comment by csonchen** [comment]
![image](https://user-images.githubusercontent.com/5915045/83592665-6ca5d300-a58d-11ea-9e19-c1ac8f2fbb40.png)
我用你的测试了一下，没有发现问题，可以的话，你提供一下代码片段 @xiaoyu1035355110

**Comment by xiaoyu1035355110** [comment]
为什么我的就不行啊  你是npm还是直接导入的包

**Comment by xiaoyu1035355110** [comment]
@SeanChense

**Comment by csonchen** [comment]
我用的就是npm安装的包，我给你写一个代码片段吧，你稍等一下

**Comment by xiaoyu1035355110** [comment]
好的, 我可以加你个好友吗  顺便咨询下你换肤的功能

**Comment by csonchen** [comment]
这是富文本组件通过npm包引入的代码片段，你打开试试：
[https://developers.weixin.qq.com/s/NFb1XPmV7Chs](url)
可以在下面地址主页私信我哈：[https://developers.weixin.qq.com/community/personal/oCJUsw6CDczLYBukymF5bLqloT8k](url)
@xiaoyu1035355110

**Comment by xiaoyu1035355110** [comment]
不支持异步的嘛? 直接写能出来  异步回来设置数据就不显示 @SeanChense

**Comment by csonchen** [comment]
你这边最好提供一个代码片段，异步还是同步，其实不关乎这个组件的具体实现，你这样我很难给你解答 @xiaoyu1035355110

**Comment by xiaoyu1035355110** [comment]
https://developers.weixin.qq.com/s/NBlWkPmW7BhF @SeanChense 你看一下你那有问题吗

**Comment by csonchen** [comment]
我大概知道问题了，稍等一下，我现在紧急修复一下 @xiaoyu1035355110

**Comment by xiaoyu1035355110** [comment]
好的  修复了 @我 @SeanChense

**Comment by csonchen** [comment]
已经修复了，你更新一下版本1.0.5 @xiaoyu1035355110 ，对了还有一个问题，你at错人了，我是csonchen哈

**Comment by xiaoyu1035355110** [comment]
哈哈  我都没看到  我一会估计还带请教你主题的问题  咋俩一直在人家的问题下面聊天 @csonchen

**Comment by xiaoyu1035355110** [comment]
还有个问题  视频和图片一起传上去  图片会盖住视频大约30px,这种问题需要我们自行修改源码? @csonchen

**Comment by csonchen** [comment]
视频标签我还真没试过，用的原来的，你可以自行改一下，我晚点去试一下 @xiaoyu1035355110

**Comment by csonchen** [comment]
我后期估计会重新整一个类似腾讯视频的视频组件出来

**Comment by xiaoyu1035355110** [comment]
哦 好的
