### ISSUE TITLE
列表解析存在异常

### ISSUE THREAD

**Issue by yuhuyuyu** [csonchen/wxParse#23]
富文本源码
![image](https://user-images.githubusercontent.com/67989582/99367893-7c279700-28f5-11eb-8b6b-9fbc9938cf4f.png)
渲染的结果
![image](https://user-images.githubusercontent.com/67989582/99367491-fd325e80-28f4-11eb-92fd-220664fd433f.png)
多出来了两条数据，不知道是不是我的使用方法存在问题 /掩面

**Comment by csonchen** [comment]
@yuhuyuyu 
我本地写了一个代码片段，没发现问题，如下图所示：
![image](https://user-images.githubusercontent.com/5915045/99371212-95cadd80-28f9-11eb-91f7-906e7a8fa856.png)

代码片段地址：https://developers.weixin.qq.com/s/Tcz6CVmL7Flz

**Comment by yuhuyuyu** [comment]
确实如此。
我这边直接把后台的富文本渲染在页面上就会出现这样的问题。
但是把富文本的内容直接` `中就在渲染就没问题。
不清楚这有什么区别，为什么会导致这样的问题。
