### ISSUE TITLE
能解析多大的富文本？

### ISSUE THREAD

**Issue by OkamiyGit** [csonchen/wxParse#25]
我原生写的小程序，现在后台上传五花八门编辑好的页面，有的4-6M，要么解析不处理，要么卡半天，，我用的richtext，不知道这个目前可以解析多大的文件（很多背景动画解析不出来，这个问题不知道会是否存在）

**Comment by csonchen** [comment]
我记得没错的话，setData支持最大的数据传输量是1m还是2m，我这个解析的原理是递归设值，所以在一定程度上避免了批量传输的数据量，但是我也不知道极限值是多少；但是如果你的标签过于深，估计会导致页面卡顿，毕竟小程序本身也不建议过多的节点展示，这是小程序的底层所能决定的
