### ISSUE TITLE
点击图片放大之后，在当前图片手势拖拽会触发下拉刷新页面

### ISSUE THREAD

**Issue by qq31311137** [csonchen/wxParse#34]
1. 图片放大之后，滚动会触发下拉刷新页面，是否可考虑点击图片时候 triggerEvent 一个函数，用来区分是否进入模式

**Comment by csonchen** [comment]
> 1. 图片放大之后，滚动会触发下拉刷新页面，是否可考虑点击图片时候 triggerEvent 一个函数，用来区分是否进入模式

可以实现，我记录一下

**Comment by csonchen** [comment]
> 1. 图片放大之后，滚动会触发下拉刷新页面，是否可考虑点击图片时候 triggerEvent 一个函数，用来区分是否进入模式

我今早尝试了一下，图片大图下拉过程中并没有造成底层页面的下拉，你这边可以提供一下测试用例吗，最好是一个在线的代码片段
