### ISSUE TITLE
预览图片函数 wxParseImgTap 获取新增的 properties 一直为内置默认值，不响应父组件传值

### ISSUE THREAD

**Issue by jingguangyan** [csonchen/wxParse#35]
预览图片函数 wxParseImgTap 获取新增的 properties 一直为内置默认值，不响应父组件传值

**Comment by jingguangyan** [comment]
> 预览图片函数 wxParseImgTap 获取新增的 properties 一直为内置默认值，不响应父组件传值

原来是因为递归渲染 wxParse 组件，只有 nodes 这一个 properties传递下去了，所以在 wxParseImgTap 执行时获取到的一直是内置默认值

**Comment by csonchen** [comment]
> > 预览图片函数 wxParseImgTap 获取新增的 properties 一直为内置默认值，不响应父组件传值
> 
> 原来是因为递归渲染 wxParse 组件，只有 nodes 这一个 properties传递下去了，所以在 wxParseImgTap 执行时获取到的一直是内置默认值
每个独立的dom节点都是一个单独的wxParse组件，所以除了首次的nodes文本传值是html字符串以外，其余的都是js对象解析，所以你是想要实现什么功能？

**Comment by csonchen** [comment]
> > 预览图片函数 wxParseImgTap 获取新增的 properties 一直为内置默认值，不响应父组件传值
> 
> 原来是因为递归渲染 wxParse 组件，只有 nodes 这一个 properties传递下去了，所以在 wxParseImgTap 执行时获取到的一直是内置默认值

每个独立的dom节点都是一个单独的wxParse组件，所以除了首次的nodes文本传值是html字符串以外，其余的都是js对象解析，所以你是想要实现什么功能
