### ISSUE TITLE
<a>标签跳转 不支持也，能帮忙看下吗？

### ISSUE THREAD

**Issue by fanfan1993** [csonchen/wxParse#39]

**Comment by csonchen** [comment]
> _No description provided._

是支持的呀，能否发一下你的富文本字符给我

**Comment by fanfan1993** [comment]
app.json 引入 "miniprogram_npm/wx-minicomponent/wxParse/webviewPage/webviewPage"，
<wxParse nodes="{{ strings }}" class="parserClass"/>

   js: strings: '<div style="text-align:center;"><img src="https://vkceyugu.cdn.bspapp.com/VKCEYUGU-uni-app-doc/d8590190-4f28-11eb-b680-7980c8a877b8.png"/><a href="https://www.baidu.com" title="我是外链跳转" target="_blank">a标签跳转（外链跳转）</a>&nbsp; <video id="video" autoplay loop controls custom-cache="{{false}}" src="https://media.w3.org/2010/05/sintel/trailer.mp4"></video></div>',

然后不跳转也 帮我看下 感谢

**Comment by csonchen** [comment]
> app.json 引入 "miniprogram_npm/wx-minicomponent/wxParse/webviewPage/webviewPage"，
> js: strings: '
> 
> ![](https://camo.githubusercontent.com/3fd139b3bca8d4c58906b0c5254c5e629674e634eac2f6e617ce7e637333adcc/68747470733a2f2f766b6365797567752e63646e2e6273706170702e636f6d2f564b4345595547552d756e692d6170702d646f632f64383539303139302d346632382d313165622d623638302d3739383063386138373762382e706e67)[a标签跳转（外链跳转）](https://www.baidu.com) 
> ',
> 然后不跳转也 帮我看下 感谢

已修复发版了，你可以更新一下版本号1.2.0，重新构建一下就可以了

**Comment by fanfan1993** [comment]
问下您，关于小程序包 npm过大这个问题 您有什么解决的办法呀，因为引入后 有0.6MB 的增加

**Comment by csonchen** [comment]
> 问下您，关于小程序包 npm过大这个问题 您有什么解决的办法呀，因为引入后 有0.6MB 的增加

其实你可以先改一下，只保留最基本的富文本解析就好，不要引入高亮的组件和markdown的解析js，这样的话会小很多，我接下来准备优化一下体积大小

**Comment by csonchen** [comment]
> 问下您，关于小程序包 npm过大这个问题 您有什么解决的办法呀，因为引入后 有0.6MB 的增加

你可以考虑先采用原生的引入方式，这样的代码没有经过压缩编译，你可以根据项目需要选择需要的组件

**Comment by fanfan1993** [comment]
我可以直接用组件的方式只要&nbsp;wxParse，引入这样就会好很多，我先试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2021年2月20日(星期六) 下午3:36
收件人: "csonchen/wxParse"<wxParse@noreply.github.com&gt;; 
抄送: "╭ダo喜歡〓 "<396300547@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [csonchen/wxParse] <a&gt;标签跳转 不支持也，能帮忙看下吗？ (#39)





  
问下您，关于小程序包 npm过大这个问题 您有什么解决的办法呀，因为引入后 有0.6MB 的增加
  
你可以考虑先采用原生的引入方式，这样的代码没有经过压缩编译，你可以根据项目需要选择需要的组件

**Comment by csonchen** [comment]
> 我可以直接用组件的方式只要&nbsp;wxParse，引入这样就会好很多，我先试试
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "notifications"<notifications@github.com&gt;; 发送时间: 2021年2月20日(星期六) 下午3:36 收件人: "csonchen/wxParse"<wxParse@noreply.github.com&gt;; 抄送: "╭ダo喜歡〓 "<396300547@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [csonchen/wxParse] <a&gt;标签跳转 不支持也，能帮忙看下吗？ (#39) 问下您，关于小程序包 npm过大这个问题 您有什么解决的办法呀，因为引入后 有0.6MB 的增加 你可以考虑先采用原生的引入方式，这样的代码没有经过压缩编译，你可以根据项目需要选择需要的组件 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

是的，你可以去看改一下源码，把markdown的解析文件也去掉，只保留基本的html文本解析就好，我过阵子优化之后再发一个版本，按需加载组件，你可以关注一下，
