### ISSUE TITLE
建议可以插件化配置

### ISSUE THREAD

**Issue by superlbr** [csonchen/wxParse#41]
dist里面代码都是压缩的，增删组件比如showdown.js不太方便。
建议参考 https://github.com/sbfkcel/towxml/blob/master/config.js，可以配置化。
1. 是否需要markdown
2. 是否需要highlight
等等

**Comment by csonchen** [comment]
> dist里面代码都是压缩的，增删组件比如showdown.js不太方便。
> 建议参考 [https://github.com/sbfkcel/towxml/blob/master/config.js，可以配置化。](https://github.com/sbfkcel/towxml/blob/master/config.js%EF%BC%8C%E5%8F%AF%E4%BB%A5%E9%85%8D%E7%BD%AE%E5%8C%96%E3%80%82)
> 
> 1. 是否需要markdown
> 2. 是否需要highlight
>    等等

嗯，我尽快撸一版新的出来

**Comment by csonchen** [comment]
> dist里面代码都是压缩的，增删组件比如showdown.js不太方便。
> 建议参考 [https://github.com/sbfkcel/towxml/blob/master/config.js，可以配置化。](https://github.com/sbfkcel/towxml/blob/master/config.js%EF%BC%8C%E5%8F%AF%E4%BB%A5%E9%85%8D%E7%BD%AE%E5%8C%96%E3%80%82)
> 
> 1. 是否需要markdown
> 2. 是否需要highlight
>    等等

已实现，欢迎使用哈
