### ISSUE TITLE
图片加载2次的问题

### ISSUE THREAD

**Issue by MoondanceZ** [csonchen/wxParse#42]
第一次加载进入页面的时候, 所有图片会加载一次
当下滑的时候, 图片又会重新再加载一次
有办法设置为懒加载吗

**Comment by csonchen** [comment]
> 第一次加载进入页面的时候, 所有图片会加载一次
> 当下滑的时候, 图片又会重新再加载一次
> 有办法设置为懒加载吗

应该不会加载两次吧，刚开始进去的时候是占位符

**Comment by MoondanceZ** [comment]
![test](https://user-images.githubusercontent.com/11675776/112565633-5ddc2580-8e18-11eb-9448-d081b2ac65ae.gif)
我传了个动图 , 可以看一下, 一进入页面所有的图片都会同时在加载
代码如下
`onLoad(options) {
    var that = this;
    wx.request({
      url: 'https://***********',
      success (res) {
        console.log(res.data.data.data.Detail)
        that.setData({
          goodDetail: res.data.data.data.Detail
        })
      }
    })
  }`

**Comment by csonchen** [comment]
> ![test](https://user-images.githubusercontent.com/11675776/112565633-5ddc2580-8e18-11eb-9448-d081b2ac65ae.gif)
> 我传了个动图 , 可以看一下, 一进入页面所有的图片都会同时在加载
> 代码如下
> `onLoad(options) { var that = this; wx.request({ url: 'https://***********', success (res) { console.log(res.data.data.data.Detail) that.setData({ goodDetail: res.data.data.data.Detail }) } }) }`

我去修复一下

**Comment by csonchen** [comment]
> ![test](https://user-images.githubusercontent.com/11675776/112565633-5ddc2580-8e18-11eb-9448-d081b2ac65ae.gif)
> 我传了个动图 , 可以看一下, 一进入页面所有的图片都会同时在加载
> 代码如下
> `onLoad(options) { var that = this; wx.request({ url: 'https://***********', success (res) { console.log(res.data.data.data.Detail) that.setData({ goodDetail: res.data.data.data.Detail }) } }) }`

已修复

**Comment by MoondanceZ** [comment]
懒加载还是没有呢

**Comment by csonchen** [comment]
> 懒加载还是没有呢

这次把懒加载 + 图片展示渐变加上了，你重新更新一下代码；你可以先用原先的方式引入，如果用npm的话，要过一会，我晚点再去发包

**Comment by MoondanceZ** [comment]
> > 懒加载还是没有呢
> 
> 这次把懒加载 + 图片展示渐变加上了，你重新更新一下代码；你可以先用原先的方式引入，如果用npm的话，要过一会，我晚点再去发包

这下可以 , 辛苦了 , 感谢
