### ISSUE TITLE
bindData函数的问题

### ISSUE THREAD

**Issue by vitoSir** [csonchen/wxParse#5]
`const bindData = (() => {
  let instance = null
  return function(bindName, data) {
    if (!instance) {
      instance = {
        [bindName]: data
      } 
    }else if(data){
      instance[bindName] = data;
    }
    return instance[bindName]
  }
})();`
解决了该函数不会进行数据更新，导致图片预览失败

**Comment by csonchen** [comment]
@vitoSir 你去提个pr吧，我帮你合并一下

**Comment by csonchen** [comment]
我已经合并了哈，谢谢了，不过有一点要注意一下，commit信息如果是修复bug的话，建议加上前缀：fixBug哈，有可能我要做归并 @vitoSir

**Comment by vitoSir** [comment]
GitHub也是第一次用，pr还是百度来怎么操作的，见笑了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"csonchen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月18日(星期四) 下午4:34
收件人:&nbsp;"csonchen/wxParse"<wxParse@noreply.github.com&gt;;
抄送:&nbsp;"vito"<775113283@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [csonchen/wxParse] bindData函数的问题 (#5)





 
我已经合并了哈，谢谢了，不过有一点要注意一下，commit信息如果是修复bug的话，建议加上前缀：fixBug哈，有可能我要做归并 @vitoSir

**Comment by csonchen** [comment]
@vitoSir 贴一下你的html文本给我，你的修复方法有问题，我先暂时去掉了

**Comment by vitoSir** [comment]
> 
> 
> @vitoSir 贴一下你的html文本给我，你的修复方法有问题，我先暂时去掉了

你需要有多篇文章才能测试出问题

**Comment by csonchen** [comment]
> > @vitoSir 贴一下你的html文本给我，你的修复方法有问题，我先暂时去掉了
> 
> 你需要有多篇文章才能测试出问题

你去看一下最上面的一个issue，提供一下有问题的富文本给我，我去看一下
