### ISSUE TITLE
对表格支持不好，排版会乱

### ISSUE THREAD

**Issue by vitoSir** [csonchen/wxParse#7]
![1VX2V_JJE4KSEHN) CDK({7](https://user-images.githubusercontent.com/33369710/84997749-8b0cf080-b181-11ea-9a76-5c2ee50d67bc.png)
排版乱了，css功底不好，也没能解决

**Comment by csonchen** [comment]
这个还真没试过原来的，我去看看，这个我来弄吧

**Comment by vitoSir** [comment]
> 
> 
> 这个还真没试过原来的，我去看看，这个我来弄吧

原来的wxParse高度会一致

**Comment by csonchen** [comment]
> > 这个还真没试过原来的，我去看看，这个我来弄吧
> 
> 原来的wxParse高度会一致

我现在去修复一下，稍等

**Comment by csonchen** [comment]
已经修复了，你重新拉下来替换一下 @vitoSir
